# -*- coding: utf-8 -*-
"""corner detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EocqtZCZrcawAAy7JQn-JF49zWIInDmX
"""

import cv2
import matplotlib.pyplot as plt

img = cv2.imread("/content/chess.jpg")

gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

dst = cv2.cornerHarris(gray,2,3,0,.04)
dst = cv2.dilate(dst,None)
img[dst>0.01 * dst.max()] = [255,0,0]
plt.figure(figsize=(10,10))
plt.imshow(img)

img = cv2.imread("/content/download (3).jpg")

gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

dst = cv2.cornerHarris(gray,2,3,0,.04)
dst = cv2.dilate(dst,None)
img[dst>0.01 * dst.max()] = [255,0,0]
plt.figure(figsize=(10,10))
plt.imshow(img)

img = cv2.imread("/content/edge-detect.png.img.png")

gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

dst = cv2.cornerHarris(gray,2,3,0,.04)
dst = cv2.dilate(dst,None)
img[dst>0.01 * dst.max()] = [255,0,0]
plt.figure(figsize=(10,10))
plt.imshow(img)