# -*- coding: utf-8 -*-
"""face detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xs88Mt3bpGe1NZo59y-4xkNZs7PGCVtj
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

facecascade = cv2.CascadeClassifier('/content/face.xml')

img = cv2.imread("/content/download.jpg")
img2 = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
plt.imshow(img2)

face_img=img2.copy()
face_rect = facecascade.detectMultiScale(face_img,scaleFactor = 1.2, minNeighbors = 5)
for (x,y,w,h) in face_rect:
  cv2.rectangle(face_img,(x,y),(x+w,y+h),(245,5,0),2)
plt.imshow(face_img)

