# -*- coding: utf-8 -*-
"""image transformations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1USaJntKa3JXT6y_Od22OdZwyTmyuSx0p
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np
img=cv2.imread("/content/cat.jfif")
height,width=img.shape[:2]
res=cv2.resize(img,(2*width,5*height),interpolation=cv2.INTER_NEAREST)
plt.imshow(img)

img=cv2.imread("/content/cat.jfif")
rows,cols,s=img.shape
M=np.float32([[1,0,50],[0,1,100]])
dst=cv2.warpAffine(img,M,(cols,rows))
plt.imshow(dst)

M=cv2.getRotationMatrix2D((cols/2,rows/2),50,1)
dst=cv2.warpAffine(img,M,(cols,rows))
plt.imshow(dst,'gray')

img=cv2.imread("/content/cat.jfif")
kernel=np.ones((5,5),np.uint8)
plt.imshow(img,'gray')

erosion=cv2.erode(img,kernel,iterations=1)
plt.imshow(erosion,'gray')

dilation=cv2.dilate(img,kernel,iterations=1)
plt.imshow(dilation,'gray')

img=cv2.imread('/content/cat.jfif')
plt.imshow(img)

opening=cv2.morphologyEx(img,cv2.MORPH_OPEN,kernel)
plt.imshow(opening)

img = cv2.imread('/content/cat.jfif')[0:150][0:120]
plt.imshow(img)

closing = cv2.morphologyEx(img,cv2.MORPH_CLOSE,kernel)
plt.imshow(closing)